insert into public.baselines (account_id,version,verdict,verdict_line,thesis,exhibits,as_of,active,review_status)
select id, coalesce((select max(version) from public.baselines b where b.account_id=a.id),0)+1,'PURSUE',
'Owned by all seven Class I railroads, operating ~177,000 pooled cars and the majority of North American intermodal well cars. The UP-NS merger forces a divestment below 49% and puts TTX under regulatory scrutiny — a governance moment with an integration agenda attached.',
'[
 {"n":"01","text":"<b>One account, every railroad relationship.</b> TTX ownership per the STB record: <b>Union Pacific 37.03%, Norfolk Southern 19.78%, CSX 19.78%, BNSF 17.4%, CN 3.2%, CPKC 2.2%, Ferromex 0.6%.</b> Five of those seven are on this roster."},
 {"n":"02","text":"<b>It owns the intermodal asset base.</b> Approximately <b>177,000 pooled railcars</b>, including over half of the well cars used for intermodal traffic in North America — the physical substrate of the intermodal horizontal."},
 {"n":"03","text":"<b>The merger creates a forced change.</b> UP and NS combined would exceed 50% of TTX, so they have committed to divest down to <b>49% or below</b>. Ownership restructuring under STB scrutiny is a governance and data-transparency moment."},
 {"n":"04","text":"<b>The financial relationship is material to owners.</b> Union Pacific''s TTX investment carrying value was approximately <b>$1.8 billion</b> at end-2023, with car-hire expense of roughly <b>$399 million</b> in 2023 — from one owner alone."}
]'::jsonb,
'[
 {"no":"A","title":"Ownership structure","headline":"Seven railroad owners, five of them on this roster — and a merger that forces the two largest to sell down.",
  "chart":{"kind":"bar","y_label":"% ownership","labels":["Union Pacific","Norfolk Southern","CSX","BNSF","CN","CPKC","Ferromex"],
    "series":[{"name":"TTX ownership","tone":"struct","values":[37.03,19.78,19.78,17.4,3.2,2.2,0.6]}]},
  "body_html":"<p>TTX is privately owned by North America''s Class I railroads and operates as the industry''s railcar cooperative under pooling authority granted by the Surface Transportation Board. Ownership percentages above are drawn from the STB decision published in the Federal Register. In share terms: UP 5,850 shares, NS and CSX 3,125 each, BNSF 2,750, CN 500. Because UP and NS combined would exceed 50%, the merger applicants have committed to divest shares to reach 49% or below and avoid a separate control application.</p><p>Founded in 1955 as Trailer Train by the Pennsylvania Railroad, renamed and restructured under an ICC-approved pooling agreement in 1974.</p>",
  "sowhat":"Credibility earned at TTX travels to every railroad on the roster simultaneously. And because TTX exists to serve its owners at cost rather than extract margin, an efficiency argument aligns with its charter instead of fighting it.",
  "sources":[{"label":"STB decision — Federal Register, 29 May 2026","url":"https://www.federalregister.gov/documents/2026/05/29/2026-10751/union-pacific-corporation-and-union-pacific-railroad-company-control-norfolk-southern-corporation"},{"label":"BNSF Form 10-Q Q2 2026 — related party transactions (SEC)","url":"https://www.sec.gov/Archives/edgar/data/0000934612/000093461226000013/bni-20260630.htm"},{"label":"TTX — Who We Are","url":"https://www.ttx.com/about/who-we-are/"}]},
 {"no":"B","title":"The technology signal","headline":"Joining the RailPulse telematics venture in October 2025 instruments a 177,000-car fleet — and raises the question of what to do with the data.",
  "body_html":"<p>TTX joined the <b>RailPulse</b> telematics joint venture in October 2025, adding the scale and fleet-management capability of the largest shared railcar provider. Executive Vice President <b>Marty Thomas</b> framed the move as a commitment to innovation and the long-term strength of the freight rail industry. TTX separately invests in industry technology intended to improve the quality and timeliness of financial and operating information for itself and for the owner railroads it reports to. Because most owners are public companies, TTX''s financial reporting must meet Sarbanes-Oxley requirements.</p>",
  "sowhat":"Telematics answers where a car is and how it is behaving. It does not answer what should happen next — repositioning, maintenance sequencing, pool allocation across seven owners. That second question is the offer.",
  "sources":[{"label":"Trains — TTX joins RailPulse","url":"https://www.trains.com/pro/mechanical/freight-cars/ttx-joins-railpulse-telematics-joint-venture/"},{"label":"TTX — Who We Are","url":"https://www.ttx.com/about/who-we-are/"}]}
]'::jsonb,'2026-05-29',true,'current'
from public.accounts a where slug='ttx';

insert into public.baselines (account_id,version,verdict,verdict_line,thesis,exhibits,as_of,active,review_status)
select id, coalesce((select max(version) from public.baselines b where b.account_id=a.id),0)+1,'PURSUE',
'A C$788M carrier mid-way through a cloud TMS replacement, with a cross-border intermodal agreement with CPKC — another customer. Two roster accounts, one lane, and a new platform to integrate around.',
'[
 {"n":"01","text":"<b>Scale is established.</b> Revenue of <b>C$788.4 million</b> per the Transport Topics for-hire ranking (data through 31 December 2025), operating 2,000+ tractors and around 10,000 trailers and containers with roughly 4,000 employees and contractors."},
 {"n":"02","text":"<b>A TMS replacement is under way.</b> Bison partnered with <b>Mastery Logistics Systems</b> to implement the cloud-based MasterMind TMS, announced April 2025, and added barcode technology for real-time freight updates in March 2025."},
 {"n":"03","text":"<b>The CPKC intermodal agreement links two customers.</b> Bison signed with Canadian Pacific Kansas City for continuous cross-border intermodal service across Canada, the US and Mexico — the intermodal horizontal made literal."},
 {"n":"04","text":"<b>Leadership changed in 2024.</b> Mike Ludwick became President and CEO effective 1 June 2024, succeeding Rob Penner who retired 31 May 2024. Chairman Don Streuber, COO Steve Zokvic, CFO Hans Andersen."}
]'::jsonb,
'[
 {"no":"A","title":"Scale and the TMS programme","headline":"C$788 million of revenue and a cloud TMS implementation in flight — integration work with a defined anchor.",
  "chart":{"kind":"bar","y_label":"C$ millions","labels":["FY2025 revenue"],
    "series":[{"name":"Bison Transport","tone":"struct","values":[788.4]}]},
  "body_html":"<p>Bison is a privately held, asset-based carrier founded in 1969, headquartered in Winnipeg, acquired by <b>James Richardson and Sons</b> in January 2021. It operates terminals, warehouses and yards across Canada, the United States and Mexico, and owns H.O. Wolding, trading as Bison Transport USA. Revenue of <b>C$788,404 thousand</b> is reported in the Transport Topics for-hire carrier ranking using data through 31 December 2025.</p><p>The company markets specifically to technology and semiconductor shippers, citing GPS tracking, geofencing, carrier vetting, controlled yard processes and real-time visibility for high-value time-sensitive freight, plus dedicated fleet solutions for just-in-time semiconductor supply and data-centre deployment projects.</p>",
  "sowhat":"A new cloud TMS is the single best time to engage: integration, data migration, analytics and AI layers are all specified in the first eighteen months after go-live. Patient family-conglomerate ownership supports multi-year platform investment.",
  "sources":[{"label":"Transport Topics for-hire ranking — Bison","url":"https://www.ttnews.com/for-hire/companies/bison/2026"},{"label":"Bison Transport company profile","url":"https://tracxn.com/d/companies/bisontransport/__ajHhMtwDm_gsWfw_rCp9IgaM7V8K190g_VfpuovioJs"},{"label":"Bison Transport — technology shippers","url":"https://www.bisontransport.com/shippers/technology"}]},
 {"no":"B","title":"The CPKC lane","headline":"A cross-border intermodal agreement with CPKC connects two Mphasis accounts through one lane.",
  "body_html":"<p>Bison announced an agreement with <b>Canadian Pacific Kansas City</b> (February 2024) to provide continuous cross-border intermodal service through Canada, the United States and Mexico. CPKC is also a Mphasis customer, making this the only place on the roster where two accounts share an operating lane.</p>",
  "sowhat":"Cross-border intermodal is a data problem before it is a rail or truck problem — customs, three regulatory regimes, equipment interchange, handoff visibility. Bison and CPKC each own one half of that lane and <b>neither owns the data that joins it</b>. One capability, two relationships.",
  "sources":[{"label":"Bison Transport news","url":"https://www.bisontransport.com/category/news"},{"label":"Bison Transport company profile","url":"https://tracxn.com/d/companies/bisontransport/__ajHhMtwDm_gsWfw_rCp9IgaM7V8K190g_VfpuovioJs"}]}
]'::jsonb,'2026-08-14',true,'current'
from public.accounts a where slug='bison';
