insert into public.baselines (account_id,version,verdict,verdict_line,thesis,exhibits,as_of,active,review_status)
select id, coalesce((select max(version) from public.baselines b where b.account_id=a.id),0)+1,'WATCH',
'A $3B manufacturer with flat revenue for five years and a 280-truck support fleet. Too small a logistics footprint to fund a programme — but they are recruiting a Transformation Program Management Director, and that is the trigger to watch.',
'[
 {"n":"01","text":"<b>Revenue is flat and the business is mature.</b> Approximately <b>$3 billion</b> in 2025, having moved between $3.0 billion and $3.2 billion since 2021, with around 13,000 employees."},
 {"n":"02","text":"<b>The fleet is a support function, not a business.</b> FMCSA records for the primary authority show <b>280 power units and 248 drivers</b> running 14,039,000 miles in 2024 — meaningful for a manufacturer, too small to fund a standalone logistics transformation."},
 {"n":"03","text":"<b>Safety compliance is already strong</b> — a Satisfactory FMCSA rating with driver and vehicle out-of-service rates below the national average, closing the safety-remediation wedge."},
 {"n":"04","text":"<b>The trigger to watch is a hire.</b> Dart has been recruiting a <b>Transformation Program Management Director</b> and a Manufacturing Reliability Director at Mason, with operations roles at their highest level in twelve months and SAP referenced among the technologies."}
]'::jsonb,
'[
 {"no":"A","title":"Business and fleet scale","headline":"$3 billion of flat revenue and a 280-truck private fleet — a manufacturer, not a logistics buyer.",
  "chart":{"kind":"bar","y_label":"$ billions revenue","labels":["2021","2022","2023","2024","2025"],
    "series":[{"name":"Revenue","tone":"dim","values":[3.0,3.2,3.2,3.0,3.0]}]},
  "body_html":"<p>Dart Container is a privately held manufacturer of single-use foodservice packaging, founded 1960 by William A. Dart, headquartered at Mason, Michigan, where the campus houses corporate headquarters, two production plants, a distribution warehouse and RandD across nearly two million square feet employing about 1,400 people. Revenue of approximately <b>$3 billion in 2025</b> per Forbes America''s Largest Private Companies (FactSet data), roughly flat since 2021. Around 13,000 employees overall. It acquired Solo Cup in 2012 and operates under the Dart, Solo, ProPlanet and Fusion brands.</p><p>The primary trucking authority, <b>Dart Container Corporation of California</b> (USDOT #217295), runs 280 power units and 248 drivers over 14,039,000 annual miles, holding a Satisfactory safety rating. No additional Dart Container carrier authorities were identified that would materially change fleet size.</p><p class=''note''>Leadership shows a source conflict: Forbes lists CEO Keith Clark, older references list Robert C. Dart. Confirm before any named approach. Note also that <i>Dart Transit Company</i> of Eagan, Minnesota is an unrelated carrier and must not be attributed to Dart Container.</p>",
  "sowhat":"At this scale the freight is a supporting function of a manufacturing business, so any conversation starts from <b>plant-to-customer supply chain and SAP</b>, not from the trucks. Set the review for the next 90-day cycle and check whether the transformation director role has been filled.",
  "sources":[{"label":"FMCSA carrier record — Dart Container Corporation of California (DOT# 217295)","url":"https://loadwrap.com/company/217295-dart-container-corporation-of-california"},{"label":"Dart Container — Mason, MI campus","url":"https://corporate.dartcontainer.com/location/mason-mi/"},{"label":"Dart Container — company profile and hiring activity","url":"https://www.zoominfo.com/c/dart-container-corp/33263647"},{"label":"Dart Container — company reference","url":"https://en.wikipedia.org/wiki/Dart_Container"}]}
]'::jsonb,'2026-08-10',true,'current'
from public.accounts a where slug='dart';
